"""init

Revision ID: 20e0118b3d26
Revises: 
Create Date: 2025-11-10 10:08:40.505646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e0118b3d26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencias_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencias_log_id'), 'asistencias_log', ['id'], unique=False)
    op.create_index(op.f('ix_asistencias_log_persona_id'), 'asistencias_log', ['persona_id'], unique=False)
    op.create_index(op.f('ix_asistencias_log_timestamp'), 'asistencias_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_asistencias_log_tipo'), 'asistencias_log', ['tipo'], unique=False)
    op.create_table('invitados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('campana_area', sa.String(length=255), nullable=True),
    sa.Column('eps', sa.String(length=255), nullable=True),
    sa.Column('sede', sa.String(length=255), nullable=True),
    sa.Column('estado_asistencia', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitados_campana_area'), 'invitados', ['campana_area'], unique=False)
    op.create_index(op.f('ix_invitados_cedula'), 'invitados', ['cedula'], unique=True)
    op.create_index(op.f('ix_invitados_eps'), 'invitados', ['eps'], unique=False)
    op.create_index(op.f('ix_invitados_id'), 'invitados', ['id'], unique=False)
    op.create_index(op.f('ix_invitados_nombre'), 'invitados', ['nombre'], unique=False)
    op.create_index(op.f('ix_invitados_sede'), 'invitados', ['sede'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('acompanantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitado_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('parentesco', sa.String(length=100), nullable=True),
    sa.Column('eps', sa.String(length=255), nullable=True),
    sa.Column('estado_asistencia', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invitado_id'], ['invitados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acompanantes_cedula'), 'acompanantes', ['cedula'], unique=True)
    op.create_index(op.f('ix_acompanantes_eps'), 'acompanantes', ['eps'], unique=False)
    op.create_index(op.f('ix_acompanantes_id'), 'acompanantes', ['id'], unique=False)
    op.create_index(op.f('ix_acompanantes_nombre'), 'acompanantes', ['nombre'], unique=False)
    op.create_index(op.f('ix_acompanantes_parentesco'), 'acompanantes', ['parentesco'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acompanantes_parentesco'), table_name='acompanantes')
    op.drop_index(op.f('ix_acompanantes_nombre'), table_name='acompanantes')
    op.drop_index(op.f('ix_acompanantes_id'), table_name='acompanantes')
    op.drop_index(op.f('ix_acompanantes_eps'), table_name='acompanantes')
    op.drop_index(op.f('ix_acompanantes_cedula'), table_name='acompanantes')
    op.drop_table('acompanantes')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_invitados_sede'), table_name='invitados')
    op.drop_index(op.f('ix_invitados_nombre'), table_name='invitados')
    op.drop_index(op.f('ix_invitados_id'), table_name='invitados')
    op.drop_index(op.f('ix_invitados_eps'), table_name='invitados')
    op.drop_index(op.f('ix_invitados_cedula'), table_name='invitados')
    op.drop_index(op.f('ix_invitados_campana_area'), table_name='invitados')
    op.drop_table('invitados')
    op.drop_index(op.f('ix_asistencias_log_tipo'), table_name='asistencias_log')
    op.drop_index(op.f('ix_asistencias_log_timestamp'), table_name='asistencias_log')
    op.drop_index(op.f('ix_asistencias_log_persona_id'), table_name='asistencias_log')
    op.drop_index(op.f('ix_asistencias_log_id'), table_name='asistencias_log')
    op.drop_table('asistencias_log')
    # ### end Alembic commands ###
